#!/bin/sh

cd "$(dirname "$0")"

if [ ! -f zlib.pl ]; then
curl -O https://raw.githubusercontent.com/acidanthera/AppleALC/master/Tools/zlib.pl
fi

if [ ! -f layout*.xml ]; then
./Make_Layout.command
fi

if [ ! -f Platforms.xml ]; then
echo Platforms.xml not found
exit
fi

for file in *.xml
do
echo "Compressing" $file
perl zlib.pl deflate "$file" > "${file%%.*}.zml.zlib"
done

#exit

echo "Restoring original AppleHDA.kext..."
sudo rm -rf /S*/L*/E*/AppleHDA.kext/Contents/Resources/*.zml.zlib
codesign --verify --no-strict  /S*/L*/E*/AppleHDA.kext/

echo "Installing..."
sudo cp *.zml.zlib /S*/L*/E*/AppleHDA.kext/Contents/Resources
sudo touch /S*/L*/E*/
sudo reboot

